### ISSUE TITLE
Move TravisCI scripts to "scripts" folder

### ISSUE THREAD

**Issue by thomscode** [pacifica/pacifica-search-drupal#19]
### Pacifica Search version
master

### Pacifica Core Software versions
master

### Platform Details
any

### Scenario:
The repository has a "scripts" folder to contain tool scripts for the project. This currently contains "composer" scripts, but the "travis" scripts folder is in the root of the repository instead of located at "scripts/travis"

### Steps to Reproduce:
* Look at the repository folder structure

### Expected Result:
* TravisCI scripts are located at `/scripts/travis`

### Actual Result:
* TravisCI scripts are located at `/travis`

**Comment by thomscode** [comment]
Is resolved by PR #21

**Comment by dmlb2000** [comment]
Fixed by #21
