### ISSUE TITLE
Need to remove composer.lock file

### ISSUE THREAD

**Issue by thomscode** [pacifica/pacifica-search-drupal#24]
### Pacifica Search version
master

### Pacifica Core Software versions
master

### Platform Details
any

### Scenario:
The `composer.lock` file is used to allow all developers on a project to use the same versions of all libraries when working together on a project. This is not desired on this project as we are creating a distribution and not using this repository to host the codebase for a specific site.

### Steps to Reproduce:
Checkout repository

### Expected Result:
No `composer.lock` file exists

### Actual Result:
`composer.lock` file exists

**Comment by dmlb2000** [comment]
Fixed by #25
