### ISSUE TITLE
We need a local-development environment

### ISSUE THREAD

**Issue by thomscode** [pacifica/pacifica-search-drupal#5]
The base Drupal installation still relies on a LAMP (or similar) environment in which to run. [Docksal] provides a containerized environment (using [Docker](https://www.docker.com/) and `docker-compose`) to setup a consistent containerized environment in which to run Drupal.

[Docksal] not only provides a local development environment, but also provides tools for managing Drupal and it's environment, as well as scripts to automatically setup and tear down the environment in a consistent way.

[Docksal]: http://docksal.io/

**Comment by dmlb2000** [comment]
This was fixed with #10
